name = "test_modpack"
author = "me mother fucker"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef0ef8f6a75c879622afdf24b076bc2d7d214771a2f627fa3828b5925dc89901"

[versions]
fabric = "0.19.2"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.1", "26.2"]
